In [1]:
!pip install open3d &> /dev/null
!pip install opencv-python &> /dev/null
!pip install matplotlib &> /dev/null

In [ ]:
import open3d as o3d
import  cv2
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import imageio.v3 as iio
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
intrinsic = o3d.camera.PinholeCameraIntrinsic(o3d.camera.PinholeCameraIntrinsicParameters.PrimeSenseDefault)
print(intrinsic.intrinsic_matrix)

[[525.    0.  319.5]
 [  0.  525.  239.5]
 [  0.    0.    1. ]]


In [ ]:
x=o3d.camera.PinholeCameraIntrinsic(640, 480, 525, 525, 320, 240)
print(x)
print(x.intrinsic_matrix)

PinholeCameraIntrinsic with width = 640 and height = 480.
Access intrinsics with intrinsic_matrix.
[[525.   0. 320.]
 [  0. 525. 240.]
 [  0.   0.   1.]]


In [ ]:
trajectory = o3d.io.read_pinhole_camera_trajectory("/content/drive/MyDrive/Colab Notebooks/images/trajectory.log")
print(trajectory.parameters[0].extrinsic)
print(trajectory.parameters[1].extrinsic)
print(trajectory.parameters[2].extrinsic)

[[ 1.  0.  0.  0.]
 [ 0.  1. -0.  0.]
 [-0.  0.  1. -0.]
 [-0. -0. -0.  1.]]
[[ 9.99991385e-01 -3.62238190e-05 -4.15016529e-03 -1.19328023e-03]
 [-1.39337391e-05  9.99926989e-01 -1.20841063e-02  2.34972516e-02]
 [ 4.15029466e-03  1.20840638e-02  9.99918374e-01  1.71970145e-03]
 [-0.00000000e+00  0.00000000e+00 -0.00000000e+00  1.00000000e+00]]
[[ 9.99969585e-01 -1.31141921e-04 -7.79848870e-03 -2.96647707e-03]
 [-5.74119318e-05  9.99707794e-01 -2.41728675e-02  4.71364433e-02]
 [ 7.79938124e-03  2.41725824e-02  9.99677372e-01  4.12249907e-03]
 [-0.00000000e+00  0.00000000e+00 -0.00000000e+00  1.00000000e+00]]


In [ ]:
pcds=[]
for i in range(211):
    im1 = o3d.io.read_image("/content/drive/MyDrive/Colab Notebooks/images/depth/{:05d}.png".format(i))
    im2 = o3d.io.read_image("/content/drive/MyDrive/Colab Notebooks/images/color/{:05d}.jpg".format(i))
    im = o3d.geometry.RGBDImage.create_from_color_and_depth(
        im2, im1, 1000.0, 5.0, False)
    pcd = o3d.geometry.PointCloud.create_from_rgbd_image(im, trajectory.parameters[i].intrinsic, trajectory.parameters[i].extrinsic)
    pcd = pcd.voxel_down_sample(voxel_size=0.2)
    pcd.transform([[-1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, -1]])
    pcds.append(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcds])

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
alpha = 0.05
pcd = np.array(pcds)
pcd.flatten()
for item in pcd:
  item = np.asarray(item)
print(pcd)
# mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(pcd, alpha)
# mesh.compute_vertex_normals()
# o3d.visualization.draw_plotly([mesh])

[PointCloud with 267 points. PointCloud with 259 points.
 PointCloud with 243 points. PointCloud with 255 points.
 PointCloud with 257 points. PointCloud with 263 points.
 PointCloud with 266 points. PointCloud with 278 points.
 PointCloud with 277 points. PointCloud with 266 points.
 PointCloud with 244 points. PointCloud with 250 points.
 PointCloud with 249 points. PointCloud with 253 points.
 PointCloud with 249 points. PointCloud with 247 points.
 PointCloud with 249 points. PointCloud with 255 points.
 PointCloud with 268 points. PointCloud with 264 points.
 PointCloud with 256 points. PointCloud with 251 points.
 PointCloud with 241 points. PointCloud with 238 points.
 PointCloud with 239 points. PointCloud with 242 points.
 PointCloud with 245 points. PointCloud with 255 points.
 PointCloud with 239 points. PointCloud with 239 points.
 PointCloud with 242 points. PointCloud with 248 points.
 PointCloud with 242 points. PointCloud with 232 points.
 PointCloud with 227 points. Po